language: php

php:
  - 5.6

env:
  - DB=mysql

# services:

# matrix:


before_script:
  - echo "Before script"
  - ls
  - date

script:
  - echo "Running test script"
  - date
  - env
#  - phpcs -p --extensions=php --standard=CakePHP ./Controller/
  - sh -c "if [ '$PHPCS' = '1' ]; then ~/.composer/vendor/bin/phpcs -p --extensions=php --standard=CakePHP ./Controller; fi;"

notifications:
  email: false
