language: php
install: composer install
cache:
  directories:
    - Vendor


php:
  - 5.5
  - 5.6

env:
  - DB=mysql

# services:

# matrix:


before_script:
  - echo "Before script"
  - composer show --installed
  - date
  - ./Vendor/bin/phpcs --config-set installed_paths $(pwd)/Vendor/cakephp/cakephp-codesniffer

  - echo "CheckStyle before script"
  #- ./Vendor/bin/phpcs -p --extensions=php --standard=CakePHP ./mediax27x
  - echo "Automation fix CheckStyle"
  #- ./Vendor/bin/phpcbf -p --extensions=php --standard=CakePHP ./mediax27x

script:
  - echo "Running test script"
  - date
  - env
  #- ./Vendor/bin/phpcs -p --extensions=php --standard=CakePHP ./mediax27x
notifications:
  email: false
