language: php

php:
  - 5.6

env:
  - DB=mysql

# services:

# matrix:


before_script:
  - echo "Before script"
  - ls
  - date

script:
  - echo "Running test script"
  - date
  - env

notifications:
  email: false
