language: php
install: composer install
cache:
  directories:
    - Vendor


php:
  - 5.5
  - 5.6

env:
  - DB=mysql

# services:

# matrix:


before_script:
  - echo "Before script"
  - composer show --installed
  - date

script:
  - echo "Running test script"
  - date
  - env
#  - phpcs -p --extensions=php --standard=CakePHP ./Controller/
  - ./Vendor/bin/phpcs -p --extensions=php --standard=CakePHP ./Controller

notifications:
  email: false
